apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegisgate.fullname" . }}-credentials
  labels:
    {{- include "aegisgate.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-url: {{ .Values.postgresql.url | toString | b64enc | quote }}
  redis-password: {{ .Values.redis.password | toString | b64enc | quote }}
  admin-key: {{ .Values.auth.adminKey | toString | b64enc | quote }}
  {{- range $i, $v := .Values.auth.apiKeys }}
  api-key-{{ $i }}: {{ $v | toString | b64enc | quote }}
  {{- end }}
